import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const scriptPath = path.join(root, 'scripts', 'prepare-local-sync.js');
const temporaryRoots = [];

function makeTemporaryPaths() {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'bookmark-local-sync-'));
  temporaryRoots.push(temporaryRoot);
  return {
    buildDir: path.join(temporaryRoot, 'build'),
    keyDir: path.join(temporaryRoot, 'keys')
  };
}

function runScript(paths) {
  return execFileSync(process.execPath, [scriptPath], {
    cwd: root,
    encoding: 'utf8',
    env: {
      ...process.env,
      BM_LOCAL_SYNC_BUILD_DIR: paths.buildDir,
      BM_LOCAL_SYNC_KEY_DIR: paths.keyDir
    }
  });
}

function runScriptExpectingFailure(paths) {
  return spawnSync(process.execPath, [scriptPath], {
    cwd: root,
    encoding: 'utf8',
    env: {
      ...process.env,
      BM_LOCAL_SYNC_BUILD_DIR: paths.buildDir,
      BM_LOCAL_SYNC_KEY_DIR: paths.keyDir
    }
  });
}

function extensionId(publicKeyDer) {
  const alphabet = 'abcdefghijklmnop';
  return crypto.createHash('sha256').update(publicKeyDer).digest('hex').slice(0, 32)
    .replace(/[0-9a-f]/g, digit => alphabet[Number.parseInt(digit, 16)]);
}

afterEach(() => {
  temporaryRoots.splice(0).forEach(temporaryRoot => fs.rmSync(temporaryRoot, { recursive: true, force: true }));
});

describe('prepare-local-sync', () => {
  it('creates a reusable stable-ID build without copying the private key', () => {
    const paths = makeTemporaryPaths();
    const firstOutput = runScript(paths);
    const firstManifest = JSON.parse(fs.readFileSync(path.join(paths.buildDir, 'manifest.json'), 'utf8'));
    const marker = JSON.parse(fs.readFileSync(path.join(paths.buildDir, '.bookmark-manager-local-sync-build'), 'utf8'));
    const privateKeyPath = path.join(paths.keyDir, 'extension-private.pem');
    const publicKeyDer = crypto.createPublicKey(
      crypto.createPrivateKey(fs.readFileSync(privateKeyPath, 'utf8'))
    ).export({ type: 'spki', format: 'der' });

    expect(firstOutput).toContain('首次生成');
    expect(firstManifest.key).toBe(publicKeyDer.toString('base64'));
    expect(marker.expectedExtensionId).toBe(extensionId(publicKeyDer));
    expect(fs.existsSync(path.join(paths.buildDir, 'js', 'background.js'))).toBe(true);
    expect(fs.existsSync(path.join(paths.buildDir, 'extension-private.pem'))).toBe(false);

    fs.rmSync(path.join(paths.buildDir, 'js', 'background.js'));
    const secondOutput = runScript(paths);
    const secondManifest = JSON.parse(fs.readFileSync(path.join(paths.buildDir, 'manifest.json'), 'utf8'));

    expect(secondOutput).toContain('已复用');
    expect(secondManifest.key).toBe(firstManifest.key);
    expect(fs.existsSync(path.join(paths.buildDir, 'js', 'background.js'))).toBe(true);
  });

  it('refuses to overwrite a directory that was not generated by this script', () => {
    const paths = makeTemporaryPaths();
    fs.mkdirSync(paths.buildDir);

    const result = runScriptExpectingFailure(paths);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('拒绝覆盖');
    expect(fs.existsSync(path.join(paths.keyDir, 'extension-private.pem'))).toBe(false);
  });

  it('refuses a key directory that could place the private key in the distributable build', () => {
    const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'bookmark-local-sync-'));
    temporaryRoots.push(temporaryRoot);
    const paths = {
      keyDir: path.join(temporaryRoot, 'shared'),
      buildDir: path.join(temporaryRoot, 'shared', 'build')
    };

    const result = runScriptExpectingFailure(paths);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('不能重叠');
  });
});
